/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * Stamps out the per-route `layout.tsx` metadata wrappers.
 *
 * Next.js resolves static `metadata` only from server components, and every
 * tool `page.tsx` is a client component, so each route needs a thin server
 * layout beside it. These files are generated rather than hand-maintained so
 * that canonical URLs and Open Graph tags can never drift apart again.
 *
 * The generated files contain no copy of their own — they call into
 * `src/lib/seo.ts`, which reads `src/lib/tools.ts`. Edit those, then re-run:
 *
 *   node src/lib/generate-layouts.js
 */
const fs = require("fs");
const path = require("path");

const libDir = __dirname;
const appDir = path.join(libDir, "..", "app");

const BANNER =
  "// Generated by src/lib/generate-layouts.js — do not edit by hand.\n" +
  "// Update src/lib/tools.ts (or categories.ts) and re-run the generator.\n";

/** Pull tool slugs out of the catalogue. Matches data entries, not the interface. */
function readToolSlugs() {
  const source = fs.readFileSync(path.join(libDir, "tools.ts"), "utf8");
  const slugs = [];
  const re = /^\s*slug:\s*"([^"]+)",/gm;
  let match;
  while ((match = re.exec(source)) !== null) slugs.push(match[1]);
  return slugs;
}

/** Static pages that aren't tools. Copy lives here because it lives nowhere else. */
const STATIC_PAGES = [
  {
    folder: "all-tools",
    title: "All Free Online Tools — Complete Directory | ToolNagri",
    description:
      "Browse all 42 free online tools: PDF, image, text, developer, calculator, SEO and network utilities. Everything runs in your browser with no signup.",
    path: "/all-tools",
  },
  {
    folder: "contact",
    title: "Contact ToolNagri — Feedback, Bugs & Tool Requests",
    description:
      "Get in touch with the ToolNagri team. Report a bug, request a new tool or send feedback about an existing one.",
    path: "/contact",
  },
  {
    folder: "privacy",
    title: "Privacy Policy | ToolNagri",
    description:
      "How ToolNagri handles your data. Most tools process files entirely in your browser and never upload them. Read what we do and do not collect.",
    path: "/privacy",
  },
  {
    folder: "terms",
    title: "Terms of Service | ToolNagri",
    description:
      "The terms covering your use of ToolNagri's free online tools, including acceptable use and limitations of liability.",
    path: "/terms",
  },
  {
    folder: "disclaimer",
    title: "Disclaimer | ToolNagri",
    description:
      "Accuracy, availability and liability disclaimers for ToolNagri's calculators, converters and utilities.",
    path: "/disclaimer",
  },
];

function writeFileIfChanged(filePath, contents) {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  if (existing === contents) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, "utf8");
  return true;
}

function toolLayout(slug) {
  return `${BANNER}import { toolMetadata } from "@/lib/seo";

export const metadata = toolMetadata("${slug}");

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
`;
}

function staticLayout(page) {
  return `${BANNER}import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: ${JSON.stringify(page.title)},
  description: ${JSON.stringify(page.description)},
  path: ${JSON.stringify(page.path)},
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
`;
}

function main() {
  const slugs = readToolSlugs();
  if (slugs.length === 0) {
    console.error("No tool slugs found in tools.ts — aborting without writing.");
    process.exit(1);
  }

  let written = 0;
  const missingPages = [];

  for (const slug of slugs) {
    const folder = path.join(appDir, slug);
    if (!fs.existsSync(path.join(folder, "page.tsx"))) missingPages.push(slug);
    if (writeFileIfChanged(path.join(folder, "layout.tsx"), toolLayout(slug))) written++;
  }

  for (const page of STATIC_PAGES) {
    const target = path.join(appDir, page.folder, "layout.tsx");
    if (writeFileIfChanged(target, staticLayout(page))) written++;
  }

  console.log(
    `Generated layouts for ${slugs.length} tools + ${STATIC_PAGES.length} static pages ` +
      `(${written} file${written === 1 ? "" : "s"} changed).`,
  );

  if (missingPages.length) {
    console.warn(
      `\nWarning: these slugs have no page.tsx yet:\n  ${missingPages.join("\n  ")}`,
    );
  }
}

main();
