import {
  Link2,
  Calculator,
  FileSpreadsheet,
  QrCode,
  Lock,
  Code2,
  FileImage,
  FileText,
  Scale,
  Globe,
  Youtube,
  Settings,
  Percent,
  Palette,
  Database,
  Type,
  ShieldCheck,
  Key,
  ArrowLeftRight,
  Laptop,
  Eye
} from "lucide-react";

export interface ToolItem {
  name: string;
  url: string;
  description: string;
  category: "Calculators" | "Image Tools" | "PDF Tools" | "Developer Tools" | "SEO Tools" | "Social Tools" | "Text Tools" | "Utility Tools";
  icon: React.ComponentType<{ className?: string }>;
  isPopular?: boolean;
  isTrending?: boolean;
  isNew?: boolean;
}

export const ALL_TOOLS: ToolItem[] = [
  {
    name: "Free URL Shortener",
    url: "/url-shortener",
    description: "Shorten long tracking links, generate QR codes, and view click metrics in real-time.",
    category: "Developer Tools",
    icon: Link2,
    isPopular: true,
    isTrending: true,
  },
  {
    name: "Age Calculator",
    url: "/age-calculator",
    description: "Determine exact age in years, months, weeks, days, and minutes with target milestones.",
    category: "Calculators",
    icon: Calculator,
    isPopular: true,
  },
  {
    name: "Loan EMI Calculator",
    url: "/emi-calculator",
    description: "Calculate monthly loan EMIs, interest payable, and total costs with payment ratio charts.",
    category: "Calculators",
    icon: FileSpreadsheet,
    isPopular: true,
    isNew: true,
  },
  {
    name: "Percentage Calculator",
    url: "/percent-calculator",
    description: "Perform common business percentage calculations (percentage change, ratios, additions, and splits).",
    category: "Calculators",
    icon: Percent,
    isNew: true,
  },
  {
    name: "QR Code Generator",
    url: "/qr-generator",
    description: "Create fully styled, high-res QR codes for URLs, text, Wi-Fi details, and contacts.",
    category: "Developer Tools",
    icon: QrCode,
    isPopular: true,
    isTrending: true,
  },
  {
    name: "Secure Password Generator",
    url: "/password-generator",
    description: "Generate highly secure, cryptographically random passkeys with customizable options.",
    category: "Developer Tools",
    icon: Lock,
    isNew: true,
  },
  {
    name: "JSON Formatter & Validator",
    url: "/json-formatter",
    description: "Format, minify, and lint check JSON payloads with local browser validation.",
    category: "Developer Tools",
    icon: Code2,
    isPopular: false,
  },
  {
    name: "Base64 Encoder & Decoder",
    url: "/base64",
    description: "Encode raw text strings to Base64 format and decode Base64 strings back to text.",
    category: "Developer Tools",
    icon: Code2,
    isNew: true,
  },
  {
    name: "Color Space Converter",
    url: "/color-converter",
    description: "Convert color codes (HEX, RGB, HSL) with real-time WCAG accessibility checks and TailwindCSS color name mapping.",
    category: "Developer Tools",
    icon: Palette,
    isNew: true,
    isPopular: true,
  },
  {
    name: "CSV to JSON / JSON to CSV",
    url: "/csv-json",
    description: "Convert tabular CSV code or files to structured JSON arrays, and serialize JSON back to CSV format.",
    category: "Developer Tools",
    icon: FileSpreadsheet,
    isNew: true,
  },
  {
    name: "SQL Formatter & Minifier",
    url: "/sql-formatter",
    description: "Format messy database queries with proper indentation or compress statements to minified strings.",
    category: "Developer Tools",
    icon: Database,
    isNew: true,
  },
  {
    name: "XML Formatter & Prettifier",
    url: "/xml-formatter",
    description: "Validate and format raw XML documents with styled line indentations client-side.",
    category: "Developer Tools",
    icon: Code2,
    isNew: true,
  },
  {
    name: "JSON to YAML / YAML to JSON",
    url: "/json-yaml",
    description: "Bi-directional formatting and conversion tool between JSON objects and YAML structures client-side.",
    category: "Developer Tools",
    icon: Code2,
    isNew: true,
  },
  {
    name: "JWT Web Token Debugger",
    url: "/jwt-debugger",
    description: "Decode, read, and verify JSON Web Token parameters securely in your browser tab.",
    category: "Developer Tools",
    icon: ShieldCheck,
    isNew: true,
  },
  {
    name: "UUID / GUID Generator",
    url: "/uuid-generator",
    description: "Generate single or bulk RFC-compliant v4 UUID/GUID keys with customization options.",
    category: "Developer Tools",
    icon: Key,
    isNew: true,
  },
  {
    name: "HTML Entity Encoder & Decoder",
    url: "/html-entities",
    description: "Convert text characters to HTML entity code representations and decode escaped strings back.",
    category: "Developer Tools",
    icon: Code2,
    isNew: true,
  },
  {
    name: "Browser User Agent Parser",
    url: "/user-agent",
    description: "Analyze browser User Agent strings to extract browser name, OS version, device type, and engine info.",
    category: "Developer Tools",
    icon: Laptop,
    isNew: true,
  },
  {
    name: "DNS Lookup Resolver",
    url: "/dns-lookup",
    description: "Lookup A, AAAA, MX, CNAME, and TXT DNS records for domains using Cloudflare DNS over HTTPS.",
    category: "Developer Tools",
    icon: Globe,
    isNew: true,
  },
  {
    name: "What is my IP Address",
    url: "/what-is-my-ip",
    description: "Quickly lookup your public IP address, geo-location coordinates, ISP, and connection properties.",
    category: "Utility Tools",
    icon: Eye,
    isNew: true,
    isPopular: true,
  },
  {
    name: "Image Compressor",
    url: "/image-compressor",
    description: "Reduce image file sizes instantly while preserving quality using client-side canvas parsing.",
    category: "Image Tools",
    icon: FileImage,
    isPopular: true,
    isTrending: true,
  },
  {
    name: "Universal Image Converter",
    url: "/image-converter",
    description: "Convert image files between formats like PNG, JPG, JPEG, WebP, and BMP client-side.",
    category: "Image Tools",
    icon: FileImage,
    isNew: true,
    isPopular: true,
  },
  {
    name: "JPG to WebP Converter",
    url: "/jpg-to-webp",
    description: "Convert JPG and PNG images into modern, highly compressed WebP files to speed up web loading.",
    category: "Image Tools",
    icon: FileImage,
    isTrending: false,
    isNew: true,
  },
  {
    name: "Base64 Image Encoder & Decoder",
    url: "/base64-image",
    description: "Upload local image files to instantly get raw Base64 data URLs, or render images from Base64 strings.",
    category: "Image Tools",
    icon: FileImage,
    isNew: true,
  },
  {
    name: "SVG Code Optimizer",
    url: "/svg-optimizer",
    description: "Optimize raw SVG vector paths, strip empty elements, check layout viewports, and minify graphics.",
    category: "Image Tools",
    icon: Code2,
    isNew: true,
  },
  {
    name: "Merge PDF Files Online",
    url: "/pdf-merge",
    description: "Combine multiple PDF documents into a single file. Drag, reorder, and merge client-side.",
    category: "PDF Tools",
    icon: FileText,
    isPopular: false,
    isNew: true,
  },
  {
    name: "Image to PDF Converter",
    url: "/image-to-pdf",
    description: "Convert PNG, JPG, and JPEG image files into a single, clean PDF document client-side.",
    category: "PDF Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "PDF Page Splitter",
    url: "/pdf-split",
    description: "Extract specific page ranges or split single pages from any PDF document client-side.",
    category: "PDF Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "PDF to Image Converter",
    url: "/pdf-to-image",
    description: "Convert pages of a PDF document into high-quality PNG or JPG images client-side.",
    category: "PDF Tools",
    icon: FileImage,
    isNew: true,
  },
  {
    name: "PDF Page Rotator",
    url: "/pdf-rotate",
    description: "Rotate specific or all pages of a PDF document by 90, 180, or 270 degrees client-side.",
    category: "PDF Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "Base64 to PDF Converter",
    url: "/base64-pdf",
    description: "Convert Base64 data streams back to PDF files, or upload a PDF to extract its Base64 code string.",
    category: "PDF Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "Multi-Unit Converter",
    url: "/unit-converter",
    description: "Convert metrics across Length, Weight, Temperature, Area, and Speed in real-time.",
    category: "Utility Tools",
    icon: Scale,
    isNew: true,
  },
  {
    name: "Time zone Converter",
    url: "/timezone-converter",
    description: "Compare and translate dates and times across major global timezones simultaneously.",
    category: "Utility Tools",
    icon: Globe,
    isNew: true,
  },
  {
    name: "Word Counter",
    url: "/word-counter",
    description: "Check word counts, character lengths, sentences, paragraphs, reading speed, and densities.",
    category: "Text Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "Character Counter",
    url: "/character-counter",
    description: "Calculate total characters with and without spaces, check lines, letters, numbers, and densities.",
    category: "Text Tools",
    icon: FileText,
  },
  {
    name: "Text Diff Checker",
    url: "/text-diff",
    description: "Compare two text blocks side-by-side to highlight word additions, removals, and changes.",
    category: "Text Tools",
    icon: ArrowLeftRight,
    isNew: true,
  },
  {
    name: "Multi-Case Text Converter",
    url: "/case-converter",
    description: "Instantly switch text cases between UPPER, lower, Title Case, camelCase, snake_case, and more.",
    category: "Text Tools",
    icon: Type,
    isNew: true,
  },
  {
    name: "Markdown to HTML Converter",
    url: "/markdown-to-html",
    description: "Convert Markdown syntax into clean HTML output with live preview rendering and one-click copy.",
    category: "Text Tools",
    icon: FileText,
    isNew: true,
  },
  {
    name: "Lorem Ipsum Generator",
    url: "/lorem-ipsum",
    description: "Generate mock placeholder copy with custom sentence, paragraph, and layout parameters.",
    category: "Text Tools",
    icon: Type,
    isNew: true,
  },
  {
    name: "Regular Expression Tester",
    url: "/regex-tester",
    description: "Test regular expressions with highlights, match lists, validation, and plain English descriptions.",
    category: "Developer Tools",
    icon: Settings,
    isNew: true,
  },
  {
    name: "YouTube Thumbnail Downloader",
    url: "/youtube-thumbnail",
    description: "Extract static preview and high-resolution thumbnail images from any YouTube URL.",
    category: "Social Tools",
    icon: Youtube,
    isTrending: true,
  },
  {
    name: "UTM Campaign URL Builder",
    url: "/utm-builder",
    description: "Build campaign URLs with Google Analytics tracking tags to analyze promotion sources.",
    category: "SEO Tools",
    icon: Settings,
    isTrending: false,
  },
  {
    name: "URL Slug Generator",
    url: "/slug-generator",
    description: "Convert text or blog post titles into clean, URL-friendly slugs client-side.",
    category: "SEO Tools",
    icon: Link2,
    isNew: true,
  },
];
