// Generated by src/lib/generate-layouts.js - do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { toolMetadata } from "@/lib/seo";

export const metadata = toolMetadata("border-radius-previewer");

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
