"use client";

import { useState, useEffect } from "react";
import ToolLayout from "@/components/ToolLayout";
import { Copy, Check, RefreshCw, FileText, Plus, Trash2, Download } from "lucide-react";
import confetti from "canvas-confetti";

interface CustomRule {
  id: string;
  userAgent: string;
  ruleType: "Allow" | "Disallow";
  path: string;
}

export default function RobotsTxtGenerator() {
  const [defaultRule, setDefaultRule] = useState<"allow" | "disallow">("allow");
  const [crawlDelay, setCrawlDelay] = useState<string>("none");
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [customRules, setCustomRules] = useState<CustomRule[]>([]);

  const [robotsContent, setRobotsContent] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let content = "# Robots.txt generated by ToolNagri\n";
    content += `# Created: ${new Date().toLocaleDateString()}\n\n`;

    // Default rule
    content += "User-agent: *\n";
    if (defaultRule === "disallow") {
      content += "Disallow: /\n";
    } else {
      content += "Disallow:\n";
    }

    if (crawlDelay !== "none") {
      content += `Crawl-delay: ${crawlDelay}\n`;
    }
    content += "\n";

    // Custom rules
    if (customRules.length > 0) {
      content += "# Custom Rules\n";
      customRules.forEach((rule) => {
        if (!rule.userAgent.trim() || !rule.path.trim()) return;
        content += `User-agent: ${rule.userAgent.trim()}\n`;
        content += `${rule.ruleType}: ${rule.path.trim()}\n\n`;
      });
    }

    // Sitemap url
    if (sitemapUrl.trim()) {
      content += `# Sitemap Directory\n`;
      content += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    setRobotsContent(content.trim());
  }, [defaultRule, crawlDelay, sitemapUrl, customRules]);

  const handleAddRule = () => {
    setCustomRules((prev) => [
      ...prev,
      {
        id: Math.random().toString(36).substring(2, 9),
        userAgent: "*",
        ruleType: "Disallow",
        path: ""
      }
    ]);
  };

  const handleUpdateRule = (id: string, key: keyof CustomRule, value: string) => {
    setCustomRules((prev) =>
      prev.map((rule) => (rule.id === id ? { ...rule, [key]: value } : rule))
    );
  };

  const handleDeleteRule = (id: string) => {
    setCustomRules((prev) => prev.filter((rule) => rule.id !== id));
  };

  const handleCopyToClipboard = () => {
    if (!robotsContent) return;
    navigator.clipboard.writeText(robotsContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!robotsContent) return;
    const blob = new Blob([robotsContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "robots.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    confetti({
      particleCount: 25,
      spread: 25,
      origin: { y: 0.8 },
      colors: ["#2563eb", "#22c55e"],
    });
  };

  const handleReset = () => {
    setDefaultRule("allow");
    setCrawlDelay("none");
    setSitemapUrl("");
    setCustomRules([]);
  };

  const howToUse = [
    "Choose default indexing rules (Allow all search bots or Disallow indexation).",
    "Define a Crawl-Delay to prevent server crashes from over-aggressive crawls.",
    "Input your absolute Sitemaps XML link url (e.g. https://yoursite.com/sitemap.xml).",
    "Click Add Custom Rule to configure restrictions on specific user-agents or folders.",
    "Examine generated output, click Copy, or click Download to save the file."
  ];

  const benefits = [
    "Builds standard, error-free robots crawling configuration files.",
    "Supports custom directives for Googlebot, Bingbot, or search spiders.",
    "Generates instant text file downloads for deployment.",
    "100% Client-Side generation keeps details private."
  ];

  const faqs = [
    {
      question: "Where should the robots.txt file be uploaded?",
      answer: "The robots.txt file must be uploaded to the root directory of your website domain (e.g. `https://example.com/robots.txt`). Search engines check this exact directory first."
    },
    {
      question: "Can robots.txt hide content from search engines?",
      answer: "Robots.txt acts as a set of recommendations. While major search crawlers (Google, Bing) respect disallow rules, malicious crawlers may ignore them. To securely protect private folders, use authentication or noindex tags."
    }
  ];

  const relatedTools = [
    { name: "Slug Generator", url: "/slug-generator", description: "Convert headlines into clean URL permalinks." },
    { name: "UTM Builder", url: "/utm-builder", description: "Build campaign tracking URLs easily." }
  ];

  return (
    <ToolLayout
      title="Robots.txt Builder"
      description="Create, structure, and generate robots.txt configuration files. Control default access rules, restrict crawling paths, set crawl delays, and append XML sitemap URLs."
      category="SEO & Marketing Tools"
      categoryUrl="/#seo"
      howToUse={howToUse}
      benefits={benefits}
      faqs={faqs}
      relatedTools={relatedTools}
    >
      <div className="space-y-6">

        {/* Configurations grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 border border-border-color rounded-2xl p-5 bg-card-bg space-y-6">
            
            <span className="text-xs font-bold text-primary-text uppercase tracking-wider border-b border-border-color pb-1.5 flex items-center gap-1.5">
              <FileText className="h-4.5 w-4.5 text-accent" /> Indexing Parameters
            </span>

            {/* Default Access and Crawl Delay */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-secondary-text uppercase tracking-wider block">Default Crawler Rule</label>
                <div className="flex rounded-lg border border-border-color p-0.5 bg-background">
                  <button
                    onClick={() => setDefaultRule("allow")}
                    className={`flex-1 py-1.5 px-3 rounded-md text-xs font-semibold cursor-pointer transition-colors ${
                      defaultRule === "allow" ? "bg-accent text-white" : "text-secondary-text hover:text-primary-text"
                    }`}
                  >
                    Allow All Crawlers
                  </button>
                  <button
                    onClick={() => setDefaultRule("disallow")}
                    className={`flex-1 py-1.5 px-3 rounded-md text-xs font-semibold cursor-pointer transition-colors ${
                      defaultRule === "disallow" ? "bg-accent text-white" : "text-secondary-text hover:text-primary-text"
                    }`}
                  >
                    Disallow All
                  </button>
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-xs font-bold text-secondary-text uppercase tracking-wider block">Crawl-Delay (Seconds)</label>
                <select
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  className="w-full py-2 px-3 rounded-lg border border-border-color bg-background text-xs text-primary-text font-semibold focus:outline-none cursor-pointer"
                >
                  <option value="none">No Delay (Default)</option>
                  <option value="5">5 Seconds</option>
                  <option value="10">10 Seconds</option>
                  <option value="15">15 Seconds</option>
                  <option value="20">20 Seconds</option>
                </select>
              </div>
            </div>

            {/* Sitemap URL */}
            <div className="space-y-1">
              <label className="text-xs font-bold text-secondary-text uppercase tracking-wider block">XML Sitemap URL</label>
              <input
                type="url"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="e.g. https://yoursite.com/sitemap.xml"
                className="w-full py-2 px-3 border border-border-color rounded-lg bg-background text-sm font-semibold text-primary-text focus:outline-none"
              />
            </div>

            {/* Custom crawling directives list */}
            <div className="space-y-3 pt-3 border-t border-border-color">
              <div className="flex justify-between items-baseline">
                <label className="text-xs font-bold text-secondary-text uppercase tracking-wider block">Custom Crawler Rules</label>
                <button
                  onClick={handleAddRule}
                  className="py-1 px-2 text-[10px] font-bold text-white bg-accent hover:bg-accent/90 rounded-md cursor-pointer flex items-center gap-1"
                >
                  <Plus className="h-3 w-3" /> Add Custom Rule
                </button>
              </div>

              {customRules.length === 0 ? (
                <p className="text-xs text-secondary-text italic py-2">No custom sub-path rules added yet.</p>
              ) : (
                <div className="space-y-3 max-h-55 overflow-y-auto pr-1">
                  {customRules.map((rule) => (
                    <div key={rule.id} className="grid grid-cols-1 sm:grid-cols-4 gap-2 items-center bg-secondary-bg/25 p-2 rounded-xl border border-border-color/60">
                      <div>
                        <input
                          type="text"
                          value={rule.userAgent}
                          onChange={(e) => handleUpdateRule(rule.id, "userAgent", e.target.value)}
                          placeholder="User-Agent (e.g. Googlebot)"
                          className="w-full py-1.5 px-2.5 border border-border-color rounded-lg bg-background text-xs font-semibold focus:outline-none"
                        />
                      </div>
                      <div>
                        <select
                          value={rule.ruleType}
                          onChange={(e) => handleUpdateRule(rule.id, "ruleType", e.target.value as any)}
                          className="w-full py-1.5 px-2 border border-border-color rounded-lg bg-background text-xs font-semibold focus:outline-none cursor-pointer"
                        >
                          <option value="Allow">Allow</option>
                          <option value="Disallow">Disallow</option>
                        </select>
                      </div>
                      <div className="sm:col-span-2 flex gap-2 items-center">
                        <input
                          type="text"
                          value={rule.path}
                          onChange={(e) => handleUpdateRule(rule.id, "path", e.target.value)}
                          placeholder="Path (e.g. /private)"
                          className="flex-1 py-1.5 px-2.5 border border-border-color rounded-lg bg-background text-xs font-semibold focus:outline-none"
                        />
                        <button
                          onClick={() => handleDeleteRule(rule.id)}
                          className="text-warning hover:text-warning/80 p-1.5 rounded hover:bg-hover-bg transition-colors cursor-pointer"
                          title="Delete rule"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

          </div>

          {/* Results Editor Code Output */}
          <div className="border border-border-color rounded-2xl p-5 bg-card-bg flex flex-col justify-between min-h-75">
            <div className="space-y-4 w-full">
              <span className="text-xs font-bold text-primary-text uppercase tracking-wider border-b border-border-color pb-1.5 flex items-center gap-1.5">
                Generated robots.txt
              </span>

              <pre className="bg-secondary-bg/30 p-3 rounded-lg border border-border-color/40 font-mono text-xs text-primary-text whitespace-pre-wrap leading-normal h-60 overflow-y-auto select-all">
                {robotsContent}
              </pre>
            </div>

            <div className="flex gap-2 pt-4">
              <button
                onClick={handleCopyToClipboard}
                className="flex-1 py-2.5 px-4 rounded-lg text-xs font-semibold border border-border-color bg-background hover:bg-hover-bg text-secondary-text hover:text-primary-text cursor-pointer transition-colors flex items-center justify-center gap-1.5"
              >
                {copied ? <Check className="h-4 w-4 text-success" /> : <Copy className="h-4 w-4" />}
                {copied ? "Copied!" : "Copy Configuration"}
              </button>
              
              <button
                onClick={handleDownload}
                className="py-2.5 px-4 rounded-lg text-xs font-semibold bg-success hover:bg-success/90 text-white cursor-pointer transition-colors flex items-center justify-center gap-1.5 shadow-sm"
              >
                <Download className="h-4 w-4" /> Download
              </button>
            </div>
          </div>
        </div>

        {/* Start over trigger */}
        {(customRules.length > 0 || sitemapUrl) && (
          <div className="flex">
            <button
              onClick={handleReset}
              className="px-4 py-2 border border-border-color hover:bg-hover-bg rounded-lg text-xs font-semibold text-secondary-text hover:text-primary-text transition-colors cursor-pointer flex items-center gap-1.5"
            >
              <RefreshCw className="h-3.5 w-3.5" /> Start Over
            </button>
          </div>
        )}

      </div>
    </ToolLayout>
  );
}
