// Generated by src/lib/generate-layouts.js — do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Contact ToolNagri — Feedback, Bugs & Tool Requests",
  description: "Get in touch with the ToolNagri team. Report a bug, request a new tool or send feedback about an existing one.",
  path: "/contact",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
