// Generated by src/lib/generate-layouts.js - do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "All Free Online Tools - Complete Directory | ToolNagri",
  description: "Browse all 44 free online tools: PDF, image, text, developer, calculator, SEO, social download and network utilities. Free with no signup.",
  path: "/all-tools",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
