// Generated by src/lib/generate-layouts.js — do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "All Free Online Tools — Complete Directory | ToolNagri",
  description: "Browse all 42 free online tools: PDF, image, text, developer, calculator, SEO and network utilities. Everything runs in your browser with no signup.",
  path: "/all-tools",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
