// Generated by src/lib/generate-layouts.js — do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Terms of Service | ToolNagri",
  description: "The terms covering your use of ToolNagri's free online tools, including acceptable use and limitations of liability.",
  path: "/terms",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
