// Generated by src/lib/generate-layouts.js — do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Privacy Policy | ToolNagri",
  description: "How ToolNagri handles your data. Most tools process files entirely in your browser and never upload them. Read what we do and do not collect.",
  path: "/privacy",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
