// Generated by src/lib/generate-layouts.js - do not edit by hand.
// Update src/lib/tools.ts (or categories.ts) and re-run the generator.
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Disclaimer | ToolNagri",
  description: "Accuracy, availability and liability disclaimers for ToolNagri's calculators, converters and utilities.",
  path: "/disclaimer",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
