export default function Disclaimer() {
  return (
    <div className="min-h-screen py-12 md:py-20 bg-background">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 space-y-8">
        
        {/* Header */}
        <div className="border-b border-border-color pb-6 space-y-2">
          <span className="text-xs font-semibold text-accent uppercase tracking-wider">Legal documents</span>
          <h1 className="text-3xl md:text-4xl font-heading font-extrabold text-primary-text">
            Disclaimer
          </h1>
          <p className="text-sm text-secondary-text">Last Updated: June 23, 2026</p>
        </div>

        {/* Content */}
        <div className="prose prose-slate max-w-none text-sm md:text-base text-secondary-text leading-relaxed space-y-6">
          <p>
            The information and tools provided on ToolNagri (https://toolnagri.vercel.app) are for general informational and utility purposes only.
          </p>

          <div className="rounded-xl border border-accent/20 bg-accent/5 p-4 text-primary-text">
            <h2 className="font-heading font-bold text-sm uppercase tracking-wider text-accent mb-2">
              Branding Note
            </h2>
            <p className="text-xs leading-relaxed">
              <strong>ToolNagri</strong> is a product of <strong>Ayodhya Serenity</strong>. ToolNagri is owned, operated, and managed by Ayodhya Serenity. All rights reserved.
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="font-heading font-bold text-lg text-primary-text">1. As-Is Availability</h2>
            <p>
              Our calculators, converters, formatting systems, and shorteners are provided on an &quot;as-is&quot; and &quot;as-available&quot; basis without warranty of any kind. While we strive to ensure calculations are correct and accurate, Ayodhya Serenity makes no guarantees regarding validity, functionality, or error-free outputs.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-heading font-bold text-lg text-primary-text">2. Limitation of Liability</h2>
            <p>
              In no event shall Ayodhya Serenity or its contributors be liable for any direct, indirect, special, incidental, or consequential damages (including loss of data or business interruption) arising out of the use or inability to use the tools on this website.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-heading font-bold text-lg text-primary-text">3. Redirect Disclaimer</h2>
            <p>
              We do not control nor inspect target destinations of shortened URLs. Users redirecting through links generated by third parties do so at their own risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-heading font-bold text-lg text-primary-text">4. Contact Details</h2>
            <p>
              If you have any feedback or reports of link violations, please contact us at:
            </p>
            <p className="font-semibold text-primary-text">
              Email: info.ayodhyaserenity@gmail.com
            </p>
          </section>
        </div>

      </div>
    </div>
  );
}
